FIX: attempt to fix failing test:
[javac] /data/jenkins/workspace/cloveretl.engine-3-5-0-M2/cloveretl.engine/test/org/jetel/util/CompareUtilsTest.java:45: incompatible types; inferred type argument(s) java.lang.Comparable<? super T> do not conform to bounds of type variable(s) T
    [javac] found   : <T>int
    [javac] required: int
    [javac] 		assertTrue(CompareUtils.compare(null, null) == 0);

git-svn-id: https://svn.javlin.eu/svn/cloveretl.opensource/branches/release-3-5-0-M2@15178 a09ad3ba-1a0f-0410-b1b9-c67202f10d70